 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/goods", type: :request do
  # Good. As you add validations to Good, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Good.create! valid_attributes
      get goods_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      good = Good.create! valid_attributes
      get good_url(good)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_good_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      good = Good.create! valid_attributes
      get edit_good_url(good)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Good" do
        expect {
          post goods_url, params: { good: valid_attributes }
        }.to change(Good, :count).by(1)
      end

      it "redirects to the created good" do
        post goods_url, params: { good: valid_attributes }
        expect(response).to redirect_to(good_url(Good.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Good" do
        expect {
          post goods_url, params: { good: invalid_attributes }
        }.to change(Good, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post goods_url, params: { good: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested good" do
        good = Good.create! valid_attributes
        patch good_url(good), params: { good: new_attributes }
        good.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the good" do
        good = Good.create! valid_attributes
        patch good_url(good), params: { good: new_attributes }
        good.reload
        expect(response).to redirect_to(good_url(good))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        good = Good.create! valid_attributes
        patch good_url(good), params: { good: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested good" do
      good = Good.create! valid_attributes
      expect {
        delete good_url(good)
      }.to change(Good, :count).by(-1)
    end

    it "redirects to the goods list" do
      good = Good.create! valid_attributes
      delete good_url(good)
      expect(response).to redirect_to(goods_url)
    end
  end
end
